# This is a config for E2B sandbox template.
# You can use template ID (599n6agqtub6wrffkd5y) or template name (react-vite-shadcn-ui) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("react-vite-shadcn-ui") # Sync sandbox
# sandbox = await AsyncSandbox.create("react-vite-shadcn-ui") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('react-vite-shadcn-ui')

team_id = "d5a86ab3-c8f9-45dd-9929-2e789a1143db"
dockerfile = "e2b.Dockerfile"
template_name = "react-vite-shadcn-ui"
template_id = "599n6agqtub6wrffkd5y"
